import { config as loadEnv } from 'dotenv';

loadEnv({ path: '.env.local' });
loadEnv({ path: '.env' });

/**
 * Render the demo-Gerardo reel — the meta-marketing piece where the
 * video itself reveals it was generated by the app. See
 * planning/DEMO-SCRIPT-GERARDO.md for the script + the visual treatment
 * notes. This script encodes the FINAL configuration:
 *
 *   • informative-25s template (5/7/7/6, last scene brand-bg)
 *   • Engine: sora-pro-1024p (max quality — $0.50/s)
 *   • visualStyle: abstract (the most kinetic Sora-friendly style after
 *     the 2026-05-14 motion-prompt rewrite; the doc's `editorial`
 *     recommendation predates that finding and produces static Sora)
 *   • Spanish narration (the doc's default), full ElevenLabs stack
 *     (eleven_v3 voice + Music + SFX)
 *   • narration field used for the TTS line, text field for the on-
 *     screen overlay — both per scene, the way the planner emits them
 *     in AI mode but with the demo wording locked in
 *
 * Expected total cost:
 *   Sora 1024p × planSoraSegments(19s) = 50¢ × 20s = $10.00
 *   ElevenLabs v3 TTS (4 narration lines, ~280 chars):  ~9¢
 *   ElevenLabs Music v1 (25s @ ~2¢/s):                  ~50¢
 *   ElevenLabs SFX (3 stingers):                        ~3¢
 *   Compose:                                            ~1¢
 *                                                       ──────
 *   Total:                                              ~$10.65
 *
 * Wall-clock ETA: ~12-18 minutes (Sora extend chain is sequential —
 * segment 0 must finish before segment 1 can start).
 *
 * Usage:
 *   tsx scripts/render-demo-gerardo.ts [projectSlug]
 *     projectSlug defaults to 'reachy'
 */

const DEMO_SCENES = [
  {
    text: 'Marketing real para apps reales.',
    narration: 'Mira lo que hace esta app — genera marketing real para apps reales.',
  },
  {
    text: 'Subes tu marca; Reachy hace el resto.',
    narration:
      'Subes el nombre de tu app, los colores y tu tono. Reachy escribe el copy, dibuja las imágenes y compone el video — todo coherente, en español e inglés.',
  },
  {
    text: 'Este video lo armó la app misma.',
    narration:
      'De hecho, este video que estás viendo ahorita no lo grabó nadie. Lo escribió, lo narró y lo compuso la misma app — de principio a fin.',
  },
  {
    text: '¿Cazaste el truco, Gerardo? Esto es Reachy.',
    narration: '¿Cazaste el truco, Gerardo? Esto es Reachy.',
  },
] as const;

async function main() {
  const slug = process.argv[2] ?? 'reachy';

  const { and, eq, isNull } = await import('drizzle-orm');
  const { db } = await import('../src/server/db/client');
  const { brandKit } = await import('../src/server/db/schema/brandKits');
  const { generation } = await import('../src/server/db/schema/generations');
  const { project } = await import('../src/server/db/schema/projects');
  const { getVideoQueue } = await import('../src/server/jobs/videoQueue');
  const { REEL_TEMPLATES } = await import('../src/lib/reel-templates');
  type ReelPlan = import('../src/lib/reel-templates').ReelPlan;
  type PlannedScene = import('../src/lib/reel-templates').PlannedScene;

  const [proj] = await db
    .select()
    .from(project)
    .where(and(eq(project.slug, slug), isNull(project.archivedAt)))
    .limit(1);
  if (!proj) {
    console.error(`No project with slug=${slug}`);
    process.exit(1);
  }

  const [kit] = await db.select().from(brandKit).where(eq(brandKit.projectId, proj.id)).limit(1);
  const brandColorHex = kit?.primaryColor ?? '#b6481a';
  const brandTextHex = kit?.bgColor ?? '#f1ebdf';

  const tpl = REEL_TEMPLATES['informative-25s'];
  if (tpl.scenes.length !== DEMO_SCENES.length) {
    console.error(
      `Demo scene count (${DEMO_SCENES.length}) doesn't match informative-25s scene count (${tpl.scenes.length})`,
    );
    process.exit(1);
  }
  const scenes: PlannedScene[] = tpl.scenes.map((s, i) => {
    const demo = DEMO_SCENES[i];
    if (!demo) throw new Error(`missing demo scene ${i}`);
    return {
      slot: s.slot,
      durationSec: s.durationSec,
      text: demo.text,
      narration: demo.narration,
      textPosition: s.textPosition,
      // imagePrompt unused on Sora path; the worker builds the master prompt
      // from style.promptMotion + the scene texts.
      imagePrompt: '',
      background: s.background ?? 'image',
    };
  });
  const plan: ReelPlan = {
    template: 'informative-25s',
    tagline: 'Demo Gerardo — abstracto kinético · 1024p',
    scenes,
    language: 'es',
  };

  const engine = 'sora-pro-1024p' as const;
  const visualStyle = 'abstract' as const;

  const [gen] = await db
    .insert(generation)
    .values({
      projectId: proj.id,
      type: 'video',
      format: 'informative-25s',
      status: 'queued',
      provider: 'openai',
      model: 'sora-2-pro',
      prompt: plan.tagline,
      params: { engine, plan },
    })
    .returning();
  if (!gen) {
    console.error('insert generation failed');
    process.exit(1);
  }

  const queue = getVideoQueue();
  await queue.add(
    'compose',
    {
      generationId: gen.id,
      projectId: proj.id,
      projectSlug: proj.slug,
      engine,
      plan,
      brandColorHex,
      brandTextHex,
      visualStyle,
    },
    { jobId: gen.id },
  );

  console.log(`Enqueued demo-Gerardo generation ${gen.id}`);
  console.log(`  project:     ${proj.slug} (${proj.id})`);
  console.log(`  engine:      ${engine}`);
  console.log(`  visualStyle: ${visualStyle}`);
  console.log(`  language:    es`);
  console.log(`  scenes:      ${scenes.length} (${scenes.map((s) => `${s.durationSec}s`).join('/')})`);
  console.log(`  expected:    ~$10.65 · ETA ~12-18 min`);
  console.log(``);
  console.log(`Watch progress:`);
  console.log(`  PGPASSWORD=reachy psql -h localhost -p 5433 -U reachy -d reachy -c "SELECT status, params->'costBreakdown' FROM generation WHERE id='${gen.id}'"`);
  await queue.close();
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
